// <auto-generated />
namespace Hospice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Attempt12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Attempt12));
        
        string IMigrationMetadata.Id
        {
            get { return "201501192201461_Attempt12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
