// <auto-generated />
namespace Hospice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Skeleton_seed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Skeleton_seed));
        
        string IMigrationMetadata.Id
        {
            get { return "201501192114332_Skeleton_seed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
